//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSetting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupSetting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string AutomationExport {
            get {
                return ResourceManager.GetString("AutomationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string AutomationFileNameExportId {
            get {
                return ResourceManager.GetString("AutomationFileNameExportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1148.
        /// </summary>
        internal static string AutomationFileNameImportId {
            get {
                return ResourceManager.GetString("AutomationFileNameImportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identities.
        /// </summary>
        internal static string AutomationIdentities {
            get {
                return ResourceManager.GetString("AutomationIdentities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^i.
        /// </summary>
        internal static string AutomationIdentitiesShortcut {
            get {
                return ResourceManager.GetString("AutomationIdentitiesShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string AutomationImport {
            get {
                return ResourceManager.GetString("AutomationImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamSpeak 3.
        /// </summary>
        internal static string AutomationName {
            get {
                return ResourceManager.GetString("AutomationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK Enter.
        /// </summary>
        internal static string AutomationOk {
            get {
                return ResourceManager.GetString("AutomationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string AutomationWarning {
            get {
                return ResourceManager.GetString("AutomationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string AutomationWarningYes {
            get {
                return ResourceManager.GetString("AutomationWarningYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup is done..
        /// </summary>
        internal static string BackupDone {
            get {
                return ResourceManager.GetString("BackupDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup processing.
        /// </summary>
        internal static string BackupTitle {
            get {
                return ResourceManager.GetString("BackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the destination folder for saving settings.
        /// </summary>
        internal static string BrowseBackupFolder_Description {
            get {
                return ResourceManager.GetString("BrowseBackupFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Identity.
        /// </summary>
        internal static string ExportIdentity {
            get {
                return ResourceManager.GetString("ExportIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Identity.
        /// </summary>
        internal static string ImportIdentity {
            get {
                return ResourceManager.GetString("ImportIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The restore is done..
        /// </summary>
        internal static string RestoreDone {
            get {
                return ResourceManager.GetString("RestoreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore processing.
        /// </summary>
        internal static string RestoreTitle {
            get {
                return ResourceManager.GetString("RestoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeamSpeak {
            get {
                object obj = ResourceManager.GetObject("TeamSpeak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
